import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const test = await new Promise<string>((resolve) => {
    setTimeout(() => resolve("test"), 500);
  });
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>from server: {test}</div>
        {children}
      </body>
    </html>
  );
}
